version: '3'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
volumes:
  ollama:

############################################################
## Pull Model
############################################################
# curl -X POST http://localhost:11434/api/pull -d '{
#   "name": "llama2:7b"
# }'

############################################################
## Get Model
############################################################
# curl http://localhost:11434/api/tags

############################################################
## Vector Embeddings
############################################################
# curl -X POST http://localhost:11434/api/embeddings -d '{
#   "model": "llama2:7b",
#   "prompt": "Here is an article about llamas..."
# }'

############################################################
## Query the model
############################################################
# curl -X POST http://localhost:11434/api/generate -d '{
#   "model": "llama2:7b",
#   "prompt":"Who won the 2001 world series"
# }'